@extends('layouts.workspace')
@section('title', __('workspace.stays_archive'))
@section('content')
@php($money=app(\App\Support\Money::class))
<div class="d-flex align-items-end justify-content-between gap-3 mb-4"><div><div class="eyebrow">{{ __('workspace.stay_control') }}</div><h1 class="page-title">{{ __('workspace.stays_archive') }}</h1><p class="page-subtitle">{{ __('workspace.stays_archive_intro') }}</p></div><a class="btn btn-light" href="{{ route('workspace.stays.index') }}"><i class="bi bi-door-open me-2"></i>{{ __('workspace.stays') }}</a></div>

<section class="surface-card occupancy-card mb-4" id="occupancyCalendar">
<div class="occupancy-toolbar"><div><div class="eyebrow">{{ __('workspace.occupancy_planning') }}</div><h2 class="section-title mt-1">{{ __('workspace.occupancy_calendar') }}</h2></div><form class="occupancy-room-filter" method="GET"><input type="hidden" name="calendar_month" value="{{ $calendarStart->format('Y-m') }}"><select class="form-select form-select-sm" name="room_id" onchange="this.form.submit()"><option value="">{{ __('workspace.all_villas') }}</option>@foreach($rooms as $room)<option value="{{ $room->id }}" @selected($selectedRoomId===$room->id)>{{ $room->displayLabel() }}</option>@endforeach</select></form></div>
<div class="occupancy-nav"><a class="btn btn-light btn-sm" href="{{ request()->fullUrlWithQuery(['calendar_month'=>$calendarStart->copy()->subMonthsNoOverflow(3)->format('Y-m')]) }}"><i class="bi bi-chevron-left"></i></a><strong>{{ $calendarStart->locale(app()->getLocale())->isoFormat('MMMM YYYY') }} — {{ $calendarStart->copy()->addMonthsNoOverflow(2)->locale(app()->getLocale())->isoFormat('MMMM YYYY') }}</strong><a class="btn btn-light btn-sm" href="{{ request()->fullUrlWithQuery(['calendar_month'=>$calendarStart->copy()->addMonthsNoOverflow(3)->format('Y-m')]) }}"><i class="bi bi-chevron-right"></i></a></div>
<div class="occupancy-scroll" data-occupancy-scroll><div class="occupancy-grid" style="--calendar-days:{{ $calendar['days']->count() }}">
<div class="occupancy-month-row"><div class="occupancy-corner">{{ __('workspace.villa') }}</div>@foreach($calendar['months'] as $month)<div class="occupancy-month" style="grid-column:span {{ $month['days'] }}">{{ $month['date']->locale(app()->getLocale())->isoFormat('MMMM YYYY') }}</div>@endforeach</div>
<div class="occupancy-day-row"><div class="occupancy-row-label"><span>{{ __('workspace.daily_load') }}</span></div>@foreach($calendar['days'] as $day)<div class="occupancy-day-head {{ $day['date']->isWeekend()?'is-weekend':'' }}"><small>{{ mb_substr($day['date']->locale(app()->getLocale())->isoFormat('dd'),0,2) }}</small><strong>{{ $day['date']->format('d') }}</strong></div>@endforeach</div>
@foreach($calendar['rooms'] as $row)@if(!$selectedRoomId||$selectedRoomId===$row['room']->id)<div class="occupancy-room-row"><div class="occupancy-row-label"><strong>{{ $row['room']->displayLabel() }}</strong></div>@foreach($row['cells'] as $index=>$cell)@php($day=$calendar['days'][$index])@if($cell['occupied'])<a class="occupancy-cell is-occupied {{ $day['date']->isWeekend()?'is-weekend':'' }}" href="{{ route('workspace.stays.show',$cell['stay_id']) }}" title="{{ $cell['label'] }}"><span class="guest-color-{{ $cell['guest_color'] }}">{{ $cell['guest_initials'] }}</span></a>@else<div class="occupancy-cell is-free {{ $day['date']->isWeekend()?'is-weekend':'' }}"></div>@endif @endforeach</div>@endif @endforeach
</div></div></section>

<div class="surface-card overflow-hidden"><div class="table-responsive"><table class="table"><thead><tr><th>{{ __('workspace.guest') }}</th><th>{{ __('workspace.room') }}</th><th>{{ __('workspace.stay_period') }}</th><th>{{ __('workspace.status_label') }}</th><th>{{ __('workspace.stay_bill') }}</th><th></th></tr></thead><tbody>
@forelse($stays as $stay)<tr><td><a class="fw-semibold small text-dark" href="{{ route('workspace.stays.show',$stay) }}">{{ $stay->guest_name }}</a></td><td><span class="room-chip">{{ $stay->room->displayLabel() }}</span></td><td class="small">{{ $stay->check_in_at->setTimezone($currentCompany->timezone)->format('d.m.Y') }} — {{ $stay->check_out_at->setTimezone($currentCompany->timezone)->format('d.m.Y') }}</td><td><span class="badge-soft-{{ $stay->status->color() }}">{{ __('workspace.stay_status.'.$stay->status->value) }}</span></td><td class="fw-semibold small">{{ $money->format((int)$stay->requests->whereIn('payment_status',['pending','invoiced'])->whereNull('refund_status')->where('status','!=',\App\Enums\RequestStatus::Cancelled)->sum('price_minor'),$currentCompany->currency) }}</td><td><a class="btn btn-light btn-sm" href="{{ route('workspace.stays.show',$stay) }}"><i class="bi bi-person-vcard"></i></a></td></tr>@empty<tr><td colspan="6"><div class="empty-builder"><h3>{{ __('workspace.stays_archive_empty') }}</h3></div></td></tr>@endforelse
</tbody></table></div></div><div class="mt-3">{{ $stays->links() }}</div>
@endsection
