<!doctype html>
<html lang="en"><head><meta charset="utf-8"><style>
@page{margin:36px}body{font-family:DejaVu Sans,sans-serif;color:#172033;font-size:12px}header{border-bottom:2px solid #172033;padding-bottom:18px;margin-bottom:28px}h1{margin:0;font-size:28px;letter-spacing:2px}.muted{color:#667085}.meta{width:100%;margin-bottom:24px}.meta td{width:50%;vertical-align:top;padding:8px 0}.label{font-size:9px;font-weight:bold;color:#667085;text-transform:uppercase;letter-spacing:1px}table.lines{width:100%;border-collapse:collapse}.lines th{text-align:left;background:#f2f4f7;padding:10px 8px;font-size:9px;text-transform:uppercase}.lines td{padding:12px 8px;border-bottom:1px solid #e4e7ec}.lines th:last-child,.lines td:last-child{text-align:right}.total{text-align:right;margin-top:22px;font-size:20px;font-weight:bold}.footer{position:fixed;bottom:0;left:0;right:0;border-top:1px solid #e4e7ec;padding-top:10px;color:#667085;font-size:9px}
</style></head><body>
<header><h1>BILL</h1><div>{{ $company->name }} · #{{ str($guestStay->public_id)->substr(0,8)->upper() }}</div><div class="muted">Issued {{ now($company->timezone)->format('F j, Y') }}</div></header>
<table class="meta"><tr><td><div class="label">Bill to</div><strong>{{ $guestStay->guest_name ?: 'Guest' }}</strong><br>{{ $guestStay->guest_email }}</td><td><div class="label">Stay details</div><strong>{{ $guestStay->room->displayName() }}</strong><br>{{ $guestStay->check_in_at->setTimezone($company->timezone)->format('M j, Y') }} - {{ $guestStay->check_out_at->setTimezone($company->timezone)->format('M j, Y') }}</td></tr></table>
<table class="lines"><thead><tr><th>Service</th><th>Date</th><th>Payment</th><th>Amount</th></tr></thead><tbody>
@forelse($orders as $order)<tr><td><strong>{{ $order->items->first()?->name_snapshot ?? $order->title }}</strong><br><span class="muted">#{{ str($order->public_id)->substr(0,8)->upper() }}</span></td><td>{{ $order->created_at->setTimezone($company->timezone)->format('M j, Y') }}</td><td>{{ $order->payment_status === 'paid' ? 'Paid' : 'Amount due' }}</td><td>{{ app(\App\Support\Money::class)->format($order->price_minor,$company->currency) }}</td></tr>@empty<tr><td colspan="4">No unpaid services.</td></tr>@endforelse
</tbody></table><div class="total">Total due: {{ app(\App\Support\Money::class)->format($total,$company->currency) }}</div>
<div class="footer">Currency: {{ $company->currency }} · Cancelled and refunded services are excluded.</div>
</body></html>
