<?php

return [
    'open_in_maps' => 'Places on Google Maps', 'maps_hint' => 'Opens in a new window',
    'language' => 'Language', 'hotel' => 'Your hotel', 'room' => 'Room', 'services' => 'Services', 'orders' => 'Requests', 'bill' => 'Bill', 'logout' => 'Log out',
    'country' => 'Your country', 'other_countries' => 'Other countries and languages', 'countries' => ['INT' => 'Other countries', 'ID' => 'Indonesia', 'RU' => 'Russia', 'UA' => 'Ukraine', 'AE' => 'UAE', 'IL' => 'Israel', 'CN' => 'China', 'KR' => 'South Korea'],
    'welcome_to' => 'Welcome to', 'access_intro' => 'Everything you need for a comfortable stay, right from your device.', 'guest_service' => 'Guest services', 'access_title' => 'Enter your room details', 'access_hint' => 'Your PIN is on the card in your room or available at reception.', 'room_number' => 'Room number', 'room_example' => 'For example, 305', 'pin' => 'PIN code', 'pin_hint' => '4 digits', 'your_name' => 'Your name', 'optional' => 'optional', 'name_hint' => 'How should we address you?', 'continue' => 'Continue', 'secure_access' => 'Secure access valid only during your stay',
    'morning' => 'Good morning', 'afternoon' => 'Good afternoon', 'evening' => 'Good evening', 'how_help' => 'How can we help?', 'catalog_intro' => 'Choose a service and the hotel team will receive a separate request.', 'quick_choice' => 'Quick choice', 'popular' => 'Popular', 'catalog' => 'Catalog', 'all_services' => 'All services', 'services_count' => ':count services', 'free' => 'Complimentary', 'minutes' => '~:count min', 'order_service' => 'Order :service', 'catalog_empty' => 'Catalog coming soon', 'catalog_empty_hint' => 'Please contact reception.', 'category_empty' => 'No services are currently available in this category.',
    'guides_eyebrow' => 'Stay inspiration', 'guides_title' => 'Bali itineraries', 'guides_count' => ':count itineraries', 'mini_guide' => 'Mini guide', 'trip_plan' => 'Trip plan', 'guide_for_stay' => 'Fits your stay', 'close' => 'Close', 'got_it' => 'Got it',
    'sections' => 'Sections',
    'mini_guides' => [
        'one_day' => ['title' => 'Bali in 1 day', 'summary' => 'Ocean, Uluwatu Temple and sunset', 'intro' => 'A compact route around southern Bali with limited driving.', 'tips' => ['Morning — a quiet beach and breakfast by the ocean.', 'Afternoon — explore the southern coast and enjoy a local lunch.', 'Evening — Uluwatu Temple, sunset and a Kecak performance.']],
        'two_days' => ['title' => 'A 2-day escape', 'summary' => 'Southern coast and cultural Ubud', 'intro' => 'Two rewarding yet comfortable days combining the ocean with Bali’s green heart.', 'tips' => ['Day 1 — beach time, Uluwatu, sunset and a coastal dinner.', 'Day 2 — Tegalalang rice terraces, central Ubud, the market and Spa.']],
        'three_days' => ['title' => 'Bali in 3 days', 'summary' => 'Coast, Ubud and highland Kintamani', 'intro' => 'A short journey through Bali’s nature, culture and changing landscapes.', 'tips' => ['Day 1 — southern beaches and an evening in Uluwatu.', 'Day 2 — Tegalalang, Ubud and Balinese art.', 'Day 3 — Kintamani, Mount Batur views and scenic stops back to the hotel.']],
        'five_days' => ['title' => 'Bali in 5 days', 'summary' => 'Ocean, culture and nature at an easy pace', 'intro' => 'A balanced plan with active days and time to recharge.', 'tips' => ['Day 1 — relax by the ocean and settle in.', 'Day 2 — Uluwatu and a sunset Kecak performance.', 'Day 3 — Ubud, Tegalalang and Spa.', 'Day 4 — Kintamani and highland scenery.', 'Day 5 — a free morning, souvenirs and a farewell dinner.']],
    ],
    'order' => 'Service request', 'order_step' => 'One service, one request', 'quantity' => 'Quantity', 'price_per_item' => 'Price per item', 'base_currency' => 'Base currency: :currency', 'approx_usd' => 'Approximate USD value', 'payment_method' => 'Payment method', 'payment_hint' => 'Choose a convenient option', 'room_charge' => 'Charge to room', 'room_charge_hint' => 'Added to your combined stay bill', 'cash' => 'Cash', 'cash_hint' => 'Pay the hotel team member', 'comment' => 'Request note', 'comment_hint' => 'For example: deliver after 2 pm', 'total' => 'Total', 'submit_order' => 'Send request', 'order_notice' => 'The hotel team will receive your request immediately.', 'order_sent' => 'Your request was sent to the hotel team.',
    'stay_history' => 'Stay history', 'my_orders' => 'My requests', 'no_orders' => 'No requests yet', 'no_orders_hint' => 'Your requests and their status will appear here.', 'choose_service' => 'Choose a service', 'order_number' => 'Request #:number', 'items_count' => ':count items',
    'bill_title' => 'Combined bill', 'bill_eyebrow' => 'For your entire stay', 'bill_intro' => 'All paid services for this guest are collected here.', 'guest' => 'Guest', 'not_specified' => 'Not specified', 'bill_empty' => 'No paid services yet', 'bill_empty_hint' => 'The total will appear after you order a paid service.', 'grand_total' => 'Services total', 'usd_estimate' => 'Approximate total in USD', 'rate_note' => 'USD conversion is an estimate. Final payment is made in the hotel’s base currency.', 'cancelled_excluded' => 'Cancelled requests are excluded.',
    'current_status' => 'Current status', 'status_title' => 'Request status', 'team_received' => 'The hotel team has received your request.', 'accepted_hint' => 'A team member accepted your request and will begin soon.', 'progress_hint' => 'Your request is now in progress.', 'waiting_hint' => 'The team needs your input or clarification.', 'completed_hint' => 'Done! We hope everything was perfect.', 'cancelled_hint' => 'This request was cancelled. Please contact reception for details.', 'order_contents' => 'Request details', 'created_at' => 'Created :date', 'progress' => 'Progress', 'updated_by_team' => 'Updated by the hotel team', 'created_via_catalog' => 'Request created from the catalog', 'need_help' => 'Need help?', 'help_hint' => 'Please call reception from your room phone.',
    'status' => ['new' => 'New', 'accepted' => 'Accepted', 'in_progress' => 'In progress', 'waiting_guest' => 'Waiting for guest', 'completed' => 'Completed', 'cancelled' => 'Cancelled'],
    'calls_unavailable_title' => 'Calls are temporarily unavailable', 'calls_unavailable' => 'We are already working on this feature. For now, please contact reception.', 'back_to_services' => 'Back to services',
    'invalid_access' => 'The room number or PIN does not match.', 'invalid_stay_access' => 'No active stay matches this room and PIN.', 'stay_until' => 'Until', 'too_many_attempts' => 'Too many attempts. Please try again in one minute.', 'access_required' => 'Enter your room number and PIN to continue.',
];
