@extends('layouts.admin')
@section('title','Настройки платформы')
@section('content')
<div class="mb-4"><div class="eyebrow">Система</div><h1 class="page-title">Настройки платформы</h1><p class="page-subtitle">Общие параметры новых компаний и каналов уведомлений.</p></div>
<form method="POST" action="{{ route('platform.settings.update') }}">@csrf @method('PUT')
<div class="row g-3"><div class="col-xl-8"><div class="surface-card overflow-hidden">
<section class="form-section"><div class="form-section-title">Основные параметры</div><div class="form-section-copy">Название и контакт поддержки платформы.</div><div class="row g-3"><div class="col-md-6"><label class="form-label">Название платформы</label><input class="form-control" name="platform_name" value="{{ old('platform_name',$settings['platform_name']) }}" required></div><div class="col-md-6"><label class="form-label">Email поддержки</label><input class="form-control" type="email" name="support_email" value="{{ old('support_email',$settings['support_email']) }}" required></div></div></section>
<section class="form-section"><div class="form-section-title">Новые компании</div><div class="form-section-copy">Значения по умолчанию при подключении нового отеля.</div><div class="row g-3"><div class="col-md-4"><label class="form-label">Пробный период, дней</label><input class="form-control" type="number" min="1" max="365" name="default_trial_days" value="{{ old('default_trial_days',$settings['default_trial_days']) }}"></div><div class="col-md-4"><label class="form-label">Часовой пояс</label><select class="form-select" name="default_timezone">@foreach(['Asia/Makassar'=>'Bali / Makassar','Asia/Jakarta'=>'Jakarta','Europe/Moscow'=>'Moscow','UTC'=>'UTC'] as $value=>$label)<option value="{{ $value }}" @selected(old('default_timezone',$settings['default_timezone'])===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Валюта</label><select class="form-select" name="default_currency">@foreach(['IDR'=>'Rp (IDR)','USD'=>'USD','EUR'=>'EUR','AUD'=>'AUD'] as $currency=>$label)<option value="{{ $currency }}" @selected(old('default_currency',$settings['default_currency'])===$currency)>{{ $label }}</option>@endforeach</select></div></div></section>
</div></div><div class="col-xl-4"><div class="surface-card p-4"><h2 class="section-title">Уведомления</h2><p class="text-secondary small mt-2">Глобально включайте каналы для всех компаний.</p><div class="form-check form-switch mt-4"><input type="hidden" name="email_notifications_enabled" value="0"><input class="form-check-input" type="checkbox" name="email_notifications_enabled" value="1" id="emailEnabled" @checked($settings['email_notifications_enabled'])><label class="form-check-label" for="emailEnabled">Email-уведомления</label></div><div class="form-check form-switch mt-3"><input type="hidden" name="push_notifications_enabled" value="0"><input class="form-check-input" type="checkbox" name="push_notifications_enabled" value="1" id="pushEnabled" @checked($settings['push_notifications_enabled'])><label class="form-check-label" for="pushEnabled">Push-уведомления</label></div><button class="btn btn-primary w-100 mt-4">Сохранить настройки</button></div></div></div>
</form>
@endsection
