@extends('layouts.workspace')
@section('title',__('workspace.overview'))
@section('content')
<div class="d-flex align-items-end justify-content-between gap-3 mb-4"><div><div class="eyebrow">{{ __('workspace.operations_center') }}</div><h1 class="page-title">{{ __('workspace.hello',['name'=>str(auth()->user()->name)->before(' ')]) }}</h1><p class="page-subtitle">{{ __('workspace.dashboard_intro') }}</p></div><div class="page-actions"><a class="btn btn-primary" href="{{ route('workspace.requests.index') }}" data-open-request-modal><i class="bi bi-plus-lg me-sm-2"></i><span>{{ __('workspace.new_request') }}</span></a></div></div>
<div class="row g-3 mb-4">
@foreach([[__('workspace.new_requests'),$stats['new'],'bi-inbox',__('workspace.need_attention'),'metric-blue'],[__('workspace.active_requests'),$stats['active'],'bi-lightning-charge',__('workspace.active'),'metric-amber'],[__('workspace.overdue'),$stats['overdue'],'bi-exclamation-triangle',__('workspace.check_sla'),'metric-red'],[__('workspace.completed_today'),$stats['completed_today'],'bi-check2-circle',__('workspace.during_shift'),'metric-green']] as $metric)
<div class="col-6 col-xl-3"><div class="surface-card metric-card"><div class="d-flex justify-content-between"><span class="metric-icon {{ $metric[4] }}"><i class="bi {{ $metric[2] }}"></i></span><span class="metric-trend">{{ $metric[3] }}</span></div><div class="metric-value">{{ $metric[1] }}</div><div class="metric-label">{{ $metric[0] }}</div></div></div>
@endforeach</div>
<div class="row g-3">
<div class="col-xl-8"><div class="surface-card overflow-hidden h-100"><div class="d-flex align-items-center justify-content-between p-4 border-bottom"><div><h2 class="section-title">{{ __('workspace.recent_requests') }}</h2><div class="text-secondary mt-1" style="font-size:12px">{{ __('workspace.all_rooms_events') }}</div></div><a class="btn btn-light btn-sm" href="{{ route('workspace.requests.index') }}">{{ __('workspace.open_board') }} <i class="bi bi-arrow-right ms-1"></i></a></div><div class="table-responsive"><table class="table"><thead><tr><th>{{ __('workspace.request') }}</th><th>{{ __('workspace.room') }}</th><th>{{ __('workspace.assignee') }}</th><th>{{ __('workspace.status_label') }}</th></tr></thead><tbody>
@forelse($recent as $item)<tr><td><a class="text-dark fw-semibold" href="{{ route('workspace.requests.show',$item) }}">{{ $item->title }}</a><div class="text-secondary" style="font-size:11px">{{ $item->created_at->diffForHumans() }}</div></td><td><span class="room-chip">{{ $item->room_number }}</span></td><td><div class="small">{{ $item->assignee?->name ?? __('workspace.unassigned') }}</div></td><td><span class="badge-soft-{{ $item->status->color() }}">{{ __('workspace.status.'.$item->status->value) }}</span></td></tr>@empty<tr><td colspan="4" class="text-center text-secondary py-5">{{ __('workspace.no_requests') }}</td></tr>@endforelse
</tbody></table></div></div></div>
<div class="col-xl-4"><div class="surface-card p-4 mb-3"><h2 class="section-title">{{ __('workspace.catalog_readiness') }}</h2><div class="d-flex align-items-center justify-content-between mt-4"><div><div class="metric-value mt-0">{{ $serviceCount }}</div><div class="metric-label">{{ __('workspace.active_services') }}</div></div><span class="metric-icon"><i class="bi bi-diagram-3"></i></span></div><a class="btn btn-light w-100 mt-4" href="{{ route('workspace.services.index') }}">{{ __('workspace.configure_tree') }}</a></div><div class="surface-card p-4"><div class="d-flex align-items-center justify-content-between"><div><h2 class="section-title">{{ __('workspace.team') }}</h2><div class="text-secondary small mt-1">{{ $teamCount }} {{ __('workspace.users_with_access') }}</div></div><div class="avatar-stack"><span class="avatar"><i class="bi bi-people"></i></span></div></div>@if(auth()->user()->isOwner())<a class="btn btn-light w-100 mt-4" href="{{ route('workspace.team.index') }}">{{ __('workspace.manage_team') }}</a>@endif</div></div>
</div>
@endsection
