@php($editing = isset($company))
<div class="surface-card overflow-hidden">
<div class="form-section"><div class="form-section-title">Данные компании</div><div class="form-section-copy">Основная информация, локаль и параметры объекта.</div><div class="row g-3">
    <div class="col-md-6"><label class="form-label">Название отеля *</label><input class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name', $company->name ?? '') }}" placeholder="Например, Nusa Bay Hotel">@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label">Юридическое название</label><input class="form-control" name="legal_name" value="{{ old('legal_name', $company->legal_name ?? '') }}" placeholder="PT Nusa Hospitality"></div>
    <div class="col-md-6"><label class="form-label">Email компании</label><input class="form-control" type="email" name="email" value="{{ old('email', $company->email ?? '') }}" placeholder="hello@hotel.com"></div>
    <div class="col-md-6"><label class="form-label">Телефон</label><input class="form-control" name="phone" value="{{ old('phone', $company->phone ?? '') }}" placeholder="+62 812 3456 7890"></div>
    <div class="col-sm-6 col-lg-3"><label class="form-label">Часовой пояс *</label><select class="form-select" name="timezone">@foreach(['Asia/Makassar'=>'Bali / Makassar','Asia/Jakarta'=>'Jakarta','Europe/Moscow'=>'Moscow','UTC'=>'UTC'] as $value=>$label)<option value="{{ $value }}" @selected(old('timezone',$company->timezone ?? $defaults['timezone'] ?? 'Asia/Makassar')===$value)>{{ $label }}</option>@endforeach</select></div>
    <div class="col-sm-6 col-lg-3"><label class="form-label">Валюта *</label><select class="form-select" name="currency">@foreach(['IDR','USD','EUR','RUB'] as $currency)<option value="{{ $currency }}" @selected(old('currency',$company->currency ?? $defaults['currency'] ?? 'IDR')===$currency)>{{ $currency }}</option>@endforeach</select></div>
    <div class="col-sm-6 col-lg-3"><label class="form-label">Количество номеров *</label><input class="form-control" type="number" min="0" name="rooms_count" value="{{ old('rooms_count',$company->rooms_count ?? 0) }}"></div>
    <div class="col-sm-6 col-lg-3"><label class="form-label">Статус *</label><select class="form-select" name="status">@foreach(\App\Enums\CompanyStatus::cases() as $status)<option value="{{ $status->value }}" @selected(old('status',$company->status->value ?? 'trial')===$status->value)>{{ $status->label() }}</option>@endforeach</select></div>
    <div class="col-md-6"><label class="form-label">Тариф *</label><select class="form-select" name="plan">@foreach(['MVP','Standard','Pro'] as $plan)<option value="{{ $plan }}" @selected(old('plan',$company->plan ?? 'MVP')===$plan)>{{ $plan }}</option>@endforeach</select></div>
</div></div>
<div class="form-section"><div class="d-flex align-items-start gap-3"><span class="metric-icon"><i class="bi bi-person-badge"></i></span><div><div class="form-section-title">Владелец компании</div><div class="form-section-copy">Главный пользователь отеля. Он сможет приглашать менеджеров на следующем этапе.</div></div></div><div class="row g-3">
    <div class="col-md-6"><label class="form-label">Имя владельца *</label><input class="form-control @error('owner_name') is-invalid @enderror" name="owner_name" value="{{ old('owner_name',$company->owner->name ?? '') }}" placeholder="Полное имя">@error('owner_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label">Email для входа *</label><input class="form-control @error('owner_email') is-invalid @enderror" type="email" name="owner_email" value="{{ old('owner_email',$company->owner->email ?? '') }}" placeholder="owner@hotel.com">@error('owner_email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label">Телефон владельца</label><input class="form-control" name="owner_phone" value="{{ old('owner_phone',$company->owner->phone ?? '') }}" placeholder="+62 812 3456 7890"></div><div class="col-md-6"></div>
    <div class="col-md-6"><label class="form-label">{{ $editing ? 'Новый пароль' : 'Временный пароль *' }}</label><input class="form-control @error('owner_password') is-invalid @enderror" type="password" name="owner_password" placeholder="Минимум 8 символов">@error('owner_password')<div class="invalid-feedback">{{ $message }}</div>@enderror @if($editing)<div class="form-hint mt-1">Оставьте пустым, чтобы не менять.</div>@endif</div>
    <div class="col-md-6"><label class="form-label">Подтверждение пароля {{ $editing ? '' : '*' }}</label><input class="form-control" type="password" name="owner_password_confirmation" placeholder="Повторите пароль"></div>
</div></div>
</div>
<div class="d-flex justify-content-end gap-2 mt-3"><a class="btn btn-light px-4" href="{{ $editing ? route('platform.companies.show',$company) : route('platform.companies.index') }}">Отмена</a><button class="btn btn-primary px-4">{{ $editing ? 'Сохранить изменения' : 'Создать компанию' }}</button></div>
