@extends('layouts.admin')
@section('title', 'Компании')
@section('content')
<div class="d-flex align-items-end justify-content-between gap-3 mb-4"><div><div class="eyebrow">Клиенты платформы</div><h1 class="page-title">Компании</h1><p class="page-subtitle">Управляйте отелями и доступом владельцев.</p></div><div class="page-actions"><a class="btn btn-primary" href="{{ route('platform.companies.create') }}"><i class="bi bi-plus-lg me-sm-2"></i><span>Добавить компанию</span></a></div></div>
<div class="surface-card overflow-hidden">
<form class="p-3 p-md-4 border-bottom" method="GET"><div class="row g-2"><div class="col-md"><div class="search-box"><i class="bi bi-search"></i><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Название, email компании или владельца"></div></div><div class="col-md-auto"><select class="form-select" name="status"><option value="">Все статусы</option>@foreach(\App\Enums\CompanyStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ $status->label() }}</option>@endforeach</select></div><div class="col-md-auto"><button class="btn btn-light h-100 px-3">Применить</button></div></div></form>
<div class="table-responsive"><table class="table"><thead><tr><th>Компания</th><th>Владелец</th><th>Тариф</th><th>Номера</th><th>Статус</th><th>Создана</th><th></th></tr></thead><tbody>
@forelse($companies as $company)
<tr><td><div class="d-flex align-items-center gap-3"><span class="company-logo">{{ mb_strtoupper(mb_substr($company->name,0,2)) }}</span><div><a class="text-dark fw-semibold" href="{{ route('platform.companies.show',$company) }}">{{ $company->name }}</a><div class="text-secondary" style="font-size:11px">{{ $company->email ?: $company->slug }}</div></div></div></td><td><div class="small fw-semibold">{{ $company->owner?->name ?? 'Не назначен' }}</div><div class="text-secondary" style="font-size:11px">{{ $company->owner?->email }}</div></td><td><span class="badge text-bg-light border">{{ $company->plan }}</span></td><td class="small fw-semibold">{{ $company->rooms_count }}</td><td><span class="badge-soft-{{ $company->status->color() }}"><span class="status-dot bg-{{ $company->status->color() }}"></span>{{ $company->status->label() }}</span></td><td class="text-secondary small">{{ $company->created_at->format('d.m.Y') }}</td><td><div class="dropdown"><button class="btn btn-light btn-sm" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></button><div class="dropdown-menu dropdown-menu-end"><a class="dropdown-item" href="{{ route('platform.companies.show',$company) }}"><i class="bi bi-eye me-2"></i>Открыть</a><a class="dropdown-item" href="{{ route('platform.companies.edit',$company) }}"><i class="bi bi-pencil me-2"></i>Редактировать</a></div></div></td></tr>
@empty<tr><td colspan="7" class="text-center py-5"><i class="bi bi-buildings fs-2 text-secondary"></i><div class="fw-semibold mt-2">Компании не найдены</div><div class="text-secondary small">Измените фильтры или создайте новую компанию.</div></td></tr>@endforelse
</tbody></table></div>
@if($companies->hasPages())<div class="p-3 border-top">{{ $companies->links() }}</div>@endif
</div>
@endsection
