@extends('layouts.admin')
@section('title', $company->name)
@section('content')
<div class="d-flex align-items-end justify-content-between gap-3 mb-4"><div><a class="text-secondary small" href="{{ route('platform.companies.index') }}"><i class="bi bi-arrow-left me-1"></i> Компании</a><div class="eyebrow mt-3">Карточка компании</div><h1 class="page-title">{{ $company->name }}</h1><p class="page-subtitle">ID {{ $company->public_id }}</p></div><div class="page-actions"><a class="btn btn-primary" href="{{ route('platform.companies.edit',$company) }}"><i class="bi bi-pencil me-sm-2"></i><span>Редактировать</span></a></div></div>
<div class="row g-3">
<div class="col-lg-8"><div class="surface-card p-4 h-100"><div class="d-flex align-items-start justify-content-between mb-4"><div class="d-flex align-items-center gap-3"><span class="company-logo" style="width:56px;height:56px;font-size:18px">{{ mb_strtoupper(mb_substr($company->name,0,2)) }}</span><div><h2 class="section-title">{{ $company->legal_name ?: $company->name }}</h2><div class="text-secondary small mt-1">{{ $company->slug }} · {{ $company->plan }}</div></div></div><span class="badge-soft-{{ $company->status->color() }}"><span class="status-dot bg-{{ $company->status->color() }}"></span>{{ $company->status->label() }}</span></div>
<div class="row g-4 pt-2"><div class="col-sm-6 col-xl-4"><div class="detail-label">Email</div><div class="detail-value">{{ $company->email ?: 'Не указан' }}</div></div><div class="col-sm-6 col-xl-4"><div class="detail-label">Телефон</div><div class="detail-value">{{ $company->phone ?: 'Не указан' }}</div></div><div class="col-sm-6 col-xl-4"><div class="detail-label">Количество номеров</div><div class="detail-value">{{ $company->rooms_count }}</div></div><div class="col-sm-6 col-xl-4"><div class="detail-label">Часовой пояс</div><div class="detail-value">{{ $company->timezone }}</div></div><div class="col-sm-6 col-xl-4"><div class="detail-label">Валюта</div><div class="detail-value">{{ $company->currency }}</div></div><div class="col-sm-6 col-xl-4"><div class="detail-label">Создана</div><div class="detail-value">{{ $company->created_at->format('d.m.Y') }}</div></div></div>
</div></div>
<div class="col-lg-4"><div class="owner-panel h-100"><div class="eyebrow" style="color:#e6bd8f">Владелец компании</div><div class="d-flex align-items-center gap-3 mt-4"><span class="avatar" style="width:50px;height:50px">{{ $company->owner ? mb_strtoupper(mb_substr($company->owner->name,0,2)) : '?' }}</span><div class="position-relative" style="z-index:1"><div class="fw-semibold">{{ $company->owner?->name ?? 'Не назначен' }}</div><div class="text-white-50 small">{{ $company->owner?->email }}</div></div></div><div class="border-top border-light border-opacity-10 mt-4 pt-4"><div class="detail-label text-white-50">Последний вход</div><div class="small fw-semibold">{{ $company->owner?->last_login_at?->diffForHumans() ?? 'Ещё не входил' }}</div></div></div></div>
<div class="col-12"><div class="surface-card p-4"><h2 class="section-title mb-3">Готовность модулей</h2><div class="row g-3">
<div class="col-md-4"><div class="p-3 rounded-3 border h-100"><div class="d-flex justify-content-between"><i class="bi bi-shield-check text-success fs-5"></i><span class="badge-soft-success">Готово</span></div><div class="fw-semibold mt-3">Platform</div><div class="text-secondary small mt-1">Компания и владелец подключены</div></div></div>
<div class="col-md-4"><div class="p-3 rounded-3 border h-100"><div class="d-flex justify-content-between"><i class="bi bi-kanban text-secondary fs-5"></i><span class="badge-soft-secondary">Этап 2</span></div><div class="fw-semibold mt-3">Workspace</div><div class="text-secondary small mt-1">Канбан, услуги и менеджеры</div></div></div>
<div class="col-md-4"><div class="p-3 rounded-3 border h-100"><div class="d-flex justify-content-between"><i class="bi bi-phone text-secondary fs-5"></i><span class="badge-soft-secondary">Этап 3</span></div><div class="fw-semibold mt-3">Guest app</div><div class="text-secondary small mt-1">Каталог и заказы из номера</div></div></div>
</div></div></div>
</div>
@endsection
