<article class="kanban-card {{ $item->archived_at ? 'is-archived' : '' }} {{ $item->clarification_requested_at ? 'needs-clarification' : '' }} {{ $item->hasRefund() ? 'has-refund' : '' }}" draggable="true" data-request-card data-status-url="{{ route('workspace.requests.status',$item) }}">
    <div class="d-flex align-items-start justify-content-between gap-2"><div class="d-flex align-items-center gap-1 flex-wrap"><span class="priority-label priority-{{ $item->priority->value }}"><span></span>{{ __('workspace.priority.'.$item->priority->value) }}</span>@if($item->archived_at)<span class="archive-label"><i class="bi bi-archive me-1"></i>{{ __('workspace.archive') }}</span>@endif @if($item->clarification_requested_at)<span class="archive-label text-warning"><i class="bi bi-exclamation-triangle-fill me-1"></i>{{ __('workspace.clarification_required') }}</span>@endif @if($item->hasRefund())<span class="archive-label text-danger"><i class="bi bi-arrow-counterclockwise me-1"></i>{{ __('workspace.refund_status.'.$item->refund_status) }}</span>@endif</div><span class="text-secondary" style="font-size:10px">#{{ str($item->public_id)->substr(0,6)->upper() }}</span></div>
    <a class="kanban-title" href="{{ route('workspace.requests.show',$item) }}" data-request-modal-link>{{ $item->title }}</a>
    @if($item->description)<p class="kanban-description">{{ str($item->description)->limit(90) }}</p>@endif
    <div class="d-flex align-items-center gap-2 flex-wrap mt-3"><span class="room-chip"><i class="bi bi-door-closed me-1"></i>{{ $item->roomDisplayLabel() }}</span>@if($item->due_at)<span class="due-chip {{ $item->isOverdue() ? 'overdue' : '' }}"><i class="bi bi-clock me-1"></i>{{ $item->due_at->format('H:i') }}</span>@endif</div>
    <div class="kanban-card-footer">
        <div class="d-flex align-items-center gap-2">@if($item->assignee)<span class="avatar avatar-sm">{{ mb_strtoupper(mb_substr($item->assignee->name,0,2)) }}</span><span class="text-truncate" style="font-size:11px">{{ $item->assignee->name }}</span>@else<span class="text-secondary" style="font-size:11px"><i class="bi bi-person-plus me-1"></i>{{ __('workspace.unassigned') }}</span>@endif</div>
        <div class="d-flex align-items-center gap-1">
            @if($item->status===\App\Enums\RequestStatus::New)<form method="POST" action="{{ route('workspace.requests.take',$item) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-primary py-1 px-2">{{ __('workspace.take') }}</button></form>@endif
            <div class="dropdown"><button class="btn btn-light btn-sm py-1 px-2" data-bs-toggle="dropdown" aria-label="{{ __('workspace.actions') }}"><i class="bi bi-three-dots"></i></button><div class="dropdown-menu dropdown-menu-end">
                @foreach(\App\Enums\RequestStatus::kanban() as $next)@continue($item->guest_stay_id && $next===\App\Enums\RequestStatus::Completed && !in_array($item->status,[\App\Enums\RequestStatus::Ready,\App\Enums\RequestStatus::WaitingGuest,\App\Enums\RequestStatus::Completed],true))<form method="POST" action="{{ route('workspace.requests.status',$item) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $next->value }}"><button class="dropdown-item" @disabled($next===$item->status)>{{ __('workspace.status.'.$next->value) }}</button></form>@endforeach<div class="dropdown-divider"></div>
                <form method="POST" action="{{ route('workspace.requests.archive',$item) }}">@csrf @method('PATCH')<input type="hidden" name="archived" value="{{ $item->archived_at ? 0 : 1 }}"><button class="dropdown-item {{ $item->archived_at ? '' : 'text-danger' }}"><i class="bi bi-{{ $item->archived_at ? 'arrow-counterclockwise' : 'archive' }} me-2"></i>{{ $item->archived_at ? __('workspace.restore') : __('workspace.archive_action') }}</button></form>
            </div></div>
        </div>
    </div>
</article>
