@php($mobile = $mobile ?? false)
@unless($mobile)<a class="brand" href="{{ route('workspace.dashboard') }}"><span class="brand-mark"><i class="bi bi-bell-fill"></i></span><span><span class="brand-name d-block">{{ str($currentCompany->name)->limit(20) }}</span><span class="brand-caption d-block">{{ __('workspace.hotel_workspace') }}</span></span></a>@endunless
<div class="sidebar-label">{{ __('workspace.work_shift') }}</div><nav>
<a class="sidebar-link {{ request()->routeIs('workspace.dashboard') ? 'active' : '' }}" href="{{ route('workspace.dashboard') }}"><i class="bi bi-grid-1x2"></i>{{ __('workspace.overview') }}</a>
<a class="sidebar-link {{ request()->routeIs('workspace.requests.*') ? 'active' : '' }}" href="{{ route('workspace.requests.index') }}"><i class="bi bi-kanban"></i>{{ __('workspace.requests') }} @php($newCount=$currentCompany->requests()->where('status','new')->count()) @if($newCount)<span class="sidebar-badge">{{ $newCount }}</span>@endif</a>
<a class="sidebar-link {{ request()->routeIs('workspace.stays.*') && !request()->routeIs('workspace.stays.archive') ? 'active' : '' }}" href="{{ route('workspace.stays.index') }}"><i class="bi bi-door-open"></i>{{ __('workspace.stays') }}</a>
<a class="sidebar-link {{ request()->routeIs('workspace.stays.archive') ? 'active' : '' }}" href="{{ route('workspace.stays.archive') }}"><i class="bi bi-archive"></i>{{ __('workspace.stays_archive') }}</a>
</nav>
<div class="sidebar-label mt-4">{{ __('workspace.management') }}</div><nav>
@if(auth()->user()->isOwner())<a class="sidebar-link {{ request()->routeIs('workspace.rooms.*') ? 'active' : '' }}" href="{{ route('workspace.rooms.index') }}"><i class="bi bi-houses"></i>{{ __('workspace.room_inventory') }}</a>@endif
<a class="sidebar-link {{ request()->routeIs('workspace.services.*') ? 'active' : '' }}" href="{{ route('workspace.services.index') }}"><i class="bi bi-diagram-3"></i>{{ __('workspace.service_tree') }}</a>
<a class="sidebar-link {{ request()->routeIs('workspace.backgrounds.*') ? 'active' : '' }}" href="{{ route('workspace.backgrounds.index') }}"><i class="bi bi-images"></i>{{ __('workspace.background_library') }}</a>
@if(auth()->user()->isOwner())<a class="sidebar-link {{ request()->routeIs('workspace.team.*') ? 'active' : '' }}" href="{{ route('workspace.team.index') }}"><i class="bi bi-people"></i>{{ __('workspace.team') }}</a>@endif
<a class="sidebar-link {{ request()->routeIs('workspace.notifications.*') ? 'active' : '' }}" href="{{ route('workspace.notifications.index') }}"><i class="bi bi-bell"></i>{{ __('workspace.notifications') }}</a>
</nav>
<div class="sidebar-user"><div class="d-flex align-items-center gap-2"><span class="avatar">{{ mb_strtoupper(mb_substr(auth()->user()->name,0,2)) }}</span><div class="overflow-hidden flex-grow-1"><div class="text-white small fw-semibold text-truncate">{{ auth()->user()->name }}</div><div class="text-white-50 text-truncate" style="font-size:10px">{{ __('workspace.role.'.auth()->user()->role->value) }}</div></div>@if(session()->has('impersonator_id'))<form method="POST" action="{{ route('impersonation.stop') }}">@csrf<button class="btn btn-sm text-white-50 p-1" title="Вернуться в админку" aria-label="Вернуться в админку"><i class="bi bi-arrow-return-left"></i></button></form>@else<form method="POST" action="{{ route('logout') }}">@csrf<button class="btn btn-sm text-white-50 p-1" aria-label="{{ __('workspace.logout') }}"><i class="bi bi-box-arrow-right"></i></button></form>@endif</div></div>
