<?php

return [
    'translations' => '다른 언어 버전', 'translations_hint' => '언어별로 이름과 문구를 다르게 작성할 수 있습니다. 빈 필드는 기본 러시아어 버전을 사용합니다.', 'localized_name' => '이름', 'localized_text' => '투숙객용 문구',
    'copy_pin' => 'PIN 복사', 'pin_not_saved' => 'PIN 설정 필요', 'new_pin_auto' => '새 PIN 또는 자동', 'change_pin' => 'PIN 변경', 'set_pin' => 'PIN 설정', 'pin_updated' => '투숙객 PIN이 업데이트되었고 이전 세션은 종료되었습니다.',
    'guide_type' => '가이드', 'add_bali_guides' => '발리 지역 가이드 추가', 'bali_guides_confirm' => '발리 10개 지역의 준비된 가이드를 추가할까요? 기존 가이드는 업데이트됩니다.', 'bali_guides_installed' => '발리 지역 가이드가 트리에 추가되었습니다.',
    'language' => '언어', 'hotel_workspace' => '호텔 워크스페이스', 'work_shift' => '근무 교대', 'service_shift' => '서비스 교대', 'overview' => '개요', 'requests' => '요청', 'management' => '관리', 'service_tree' => '서비스 카탈로그', 'team' => '팀', 'notifications' => '알림', 'logout' => '로그아웃',
    'operations_center' => '운영 센터', 'hello' => '안녕하세요, :name', 'dashboard_intro' => '현재 호텔 서비스 운영 현황입니다.', 'new_request' => '새 요청', 'new_requests' => '신규 요청', 'need_attention' => '확인 필요', 'active_requests' => '처리 중', 'active' => '활성', 'overdue' => '기한 초과', 'check_sla' => 'SLA 확인', 'completed_today' => '오늘 완료', 'during_shift' => '이번 교대', 'recent_requests' => '최근 요청', 'all_rooms_events' => '모든 객실의 새 활동', 'open_board' => '보드 열기', 'request' => '요청', 'room' => '객실', 'assignee' => '담당자', 'status_label' => '상태', 'unassigned' => '미지정', 'no_requests' => '요청이 없습니다', 'catalog_readiness' => '카탈로그 준비', 'active_services' => '개 활성 서비스', 'configure_tree' => '카탈로그 설정', 'users_with_access' => '명의 접근 사용자', 'manage_team' => '팀 관리',
    'guest_requests' => '투숙객 요청', 'kanban_intro' => '카드를 상태 간에 드래그하거나 직접 변경하세요.', 'mine_only' => '내 요청만', 'all_priorities' => '모든 우선순위', 'reset' => '초기화', 'drag_hint' => '카드를 드래그할 수 있습니다', 'manual_request_hint' => '프런트 또는 투숙객을 대신하여 요청 추가', 'room_number' => '객실 번호', 'guest_name' => '투숙객 이름', 'name_or_surname' => '이름', 'catalog_service' => '카탈로그 서비스', 'other_request' => '기타 요청', 'priority_label' => '우선순위', 'short_title' => '짧은 제목', 'title_example' => '수건 추가 요청', 'comment' => '메모', 'comment_hint' => '수량, 선호 사항 또는 기타 중요 정보', 'assign' => '담당자 지정', 'leave_unassigned' => '담당자 없이 두기', 'due_at' => '완료 기한', 'cost' => '비용, :currency', 'cancel' => '취소', 'create_request' => '요청 생성', 'take' => '접수',
    'kanban' => '요청 보드', 'created' => ':time 생성', 'manually' => '직접 생성', 'by_guest' => '투숙객 생성', 'guest' => '투숙객', 'not_specified' => '미입력', 'service' => '서비스', 'other' => '기타', 'deadline' => '기한', 'not_set' => '미설정', 'order_contents' => '주문 내역', 'items_short' => ':count개', 'free' => '무료', 'cash' => '현금', 'cash_paid' => '현금 · 즉시 결제 완료', 'room_charge' => '객실 결제', 'total' => '합계: :amount', 'status_history' => '상태 기록', 'system' => '시스템', 'request_management' => '요청 관리', 'take_to_work' => '요청 접수', 'change_note' => '변경 메모', 'save_changes' => '변경 저장',
    'events_center' => '활동 센터', 'notifications_intro' => '요청 변경과 팀 활동을 한곳에서 확인하세요.', 'read_all' => '모두 읽음', 'event' => '활동', 'no_events' => '새 활동이 없습니다', 'no_events_hint' => '요청 및 담당자 알림이 여기에 표시됩니다.',
    'guest_catalog' => '투숙객 카탈로그', 'service_builder' => '서비스 카탈로그 빌더', 'builder_intro' => '중첩 카테고리와 유료 또는 무료 서비스를 만드세요.', 'add_item' => '항목 추가', 'catalog_structure' => '카탈로그 구조', 'items_published' => ':items개 · :published개 게시', 'guest_catalog_badge' => '투숙객 카탈로그', 'empty_tree' => '카탈로그가 비어 있습니다', 'empty_tree_hint' => '음식 및 음료 같은 최상위 카테고리부터 시작하세요.', 'create_first_section' => '첫 섹션 만들기', 'how_build' => '카탈로그 구성 방법', 'tip_1' => '최상위 카테고리를 만드세요.', 'tip_2' => '하위 카테고리나 서비스를 추가하세요.', 'tip_3' => '가격과 서비스 시간을 설정하세요.', 'tip_4' => '일시적으로 제공하지 않는 항목을 숨기세요.', 'new_catalog_item' => '새 카탈로그 항목', 'category_or_service' => '카테고리 또는 주문 가능한 서비스', 'edit_item' => '카탈로그 항목 편집', 'changes_live' => '변경 사항이 구조에 즉시 반영됩니다', 'add' => '추가', 'save' => '저장', 'type' => '항목 유형', 'category' => '카테고리', 'service_type' => '서비스', 'name' => '이름', 'name_hint' => '예: 조식 주문', 'parent_category' => '상위 카테고리', 'root_level' => '최상위', 'icon' => 'Bootstrap 아이콘', 'description' => '설명', 'description_hint' => '투숙객에게 제공되는 내용과 중요 조건', 'base_price' => '기본 통화 가격, :currency', 'free_price_hint' => '0 — 무료', 'usd_hint' => '투숙객에게 예상 USD 금액도 표시됩니다.', 'sla_minutes' => 'SLA, 분', 'background' => '카드 블러 배경', 'background_food' => '음식', 'background_room' => '객실', 'background_transport' => '이동', 'background_wellness' => '웰니스', 'sort_order' => '정렬 순서', 'show_guests' => '투숙객에게 표시', 'hidden' => '숨김', 'nested_items' => '하위 항목 :count개', 'no_description' => '설명 없음', 'minutes' => ':count분', 'no_sla' => 'SLA 없음', 'edit' => '편집', 'add_inside' => '하위 항목 추가', 'delete_confirm' => '이 항목과 모든 하위 항목을 삭제할까요?', 'delete' => '삭제', 'check_data' => '입력 내용을 확인하세요.',
    'notification_new' => '새 요청', 'notification_room_request' => '객실 :room: :request', 'notification_taken' => '요청 접수됨', 'notification_taken_body' => ':actor 님이 객실 :room 요청을 접수했습니다', 'notification_status_changed' => '요청 상태 변경됨', 'notification_status_body' => '객실 :room: :status', 'notification_guest_order' => '객실 :room의 새 주문',
    'push_title' => '푸시 알림', 'push_hint' => '워크스페이스가 닫혀 있어도 이 기기에서 새 요청을 받습니다.', 'push_checking' => '기기 확인 중…', 'push_enable' => '푸시 켜기', 'push_disable' => '푸시 끄기', 'push_enabled' => '이 기기에서 푸시가 켜져 있습니다.', 'push_disabled' => '아직 푸시가 켜지지 않았습니다.', 'push_unsupported' => '워크스페이스를 PWA로 설치하거나 지원 브라우저를 사용하세요.', 'push_denied' => '기기 설정에서 알림이 차단되었습니다.', 'push_error' => '푸시 설정을 변경할 수 없습니다.', 'push_test' => '테스트', 'push_test_sent' => '테스트 푸시를 보냈습니다.', 'push_test_title' => 'Luma Push 작동 중', 'push_test_body' => '이 기기에서 새 투숙객 요청을 받습니다.',
    'email_greeting' => '안녕하세요, :name님!', 'email_attention' => '호텔 워크스페이스에 확인이 필요한 새 활동이 있습니다.', 'email_open_request' => '요청 열기', 'email_footer' => '이 알림은 :company에서 전송했습니다.',
    'request_added' => '요청이 보드에 추가되었습니다.', 'request_assigned' => '요청이 나에게 지정되었습니다.', 'request_updated' => '요청 상태가 업데이트되었습니다.', 'notifications_read' => '모든 알림을 읽음으로 표시했습니다.', 'service_added' => '서비스 카탈로그에 항목을 추가했습니다.', 'service_updated' => '카탈로그 항목을 업데이트했습니다.', 'service_deleted' => '항목과 모든 하위 항목을 삭제했습니다.', 'history_manual' => '요청을 직접 생성했습니다', 'history_taken' => '매니저가 요청을 접수했습니다', 'history_guest' => '투숙객이 카탈로그에서 주문했습니다',
    'stays' => '투숙', 'stay_control' => '투숙 관리', 'stays_intro' => '투숙 일정, 개인 PIN 및 최종 청구서를 관리합니다.', 'new_stay' => '새 투숙', 'guest_access_pin' => '투숙객 PIN', 'pin_for_room' => '객실 :room 접근', 'show_once' => '저장하세요: PIN은 한 번만 표시됩니다', 'stay_checked_in_plural' => '현재 투숙 중', 'stay_upcoming_plural' => '입실 예정', 'stay_completed_plural' => '완료', 'stay_period' => '투숙 기간', 'nights' => '박', 'stay_bill' => '청구서', 'nights_short' => '박', 'extend' => '연장', 'checkout_confirm' => '체크아웃하고 접근을 종료할까요?', 'checkout_guest' => '체크아웃', 'no_stays' => '투숙 내역이 없습니다', 'no_stays_hint' => '투숙을 만들고 개인 PIN을 전달하세요.', 'new_stay_hint' => '객실, 기간 및 개인 접근을 설정하세요', 'choose_room' => '객실 선택', 'check_in' => '체크인', 'pin_auto' => '자동', 'pin_hint' => '비워두면 자동 생성', 'create_stay' => '투숙 생성', 'stay_overlap' => '선택한 기간에 객실이 사용 중입니다.', 'stay_created' => '투숙이 생성되었습니다.', 'stay_extended' => '투숙이 연장되었습니다.', 'stay_checked_out' => '체크아웃되어 접근이 종료되었습니다.',
    'background_library' => '비주얼 스타일', 'background_library_intro' => '호텔용 통합 블러 이미지 세트를 선택하거나 자체 이미지를 업로드하세요.', 'upload_background' => '이미지 업로드', 'background_manager_readonly' => '매니저는 활성 세트를 보고 서비스에 이미지를 지정할 수 있습니다. 호텔 세트 변경은 소유자만 가능합니다.', 'in_use' => '사용 중', 'ready_pack' => '준비된 세트', 'hotel_pack' => '호텔 컬렉션', 'background_count' => '이미지 :count개', 'selected' => '선택됨', 'choose_pack' => '세트 선택', 'background_set_empty' => '먼저 이미지를 하나 이상 추가하세요.', 'background_set_activated' => '“:name” 세트가 활성화되었습니다.', 'custom_backgrounds' => '내 호텔', 'background_uploaded' => '호텔 컬렉션에 이미지가 추가되었습니다.', 'background_deleted' => '이미지가 삭제되었습니다.', 'delete_background_confirm' => '이 이미지를 삭제할까요?', 'own_backgrounds' => '호텔 자체 이미지', 'own_backgrounds_intro' => '객실, 레스토랑, 이동 서비스 또는 스파 사진을 업로드하세요. 귀사에서만 사용할 수 있습니다.', 'background_name' => '이미지 이름', 'background_name_hint' => '예: Pool Villa', 'image_file' => '이미지 파일', 'upload' => '업로드', 'manage_backgrounds' => '세트 관리', 'inherit_background' => '상위 카테고리 / 호텔 세트',
    'stay_status' => ['upcoming' => '예정', 'checked_in' => '투숙 중', 'checked_out' => '체크아웃', 'cancelled' => '취소'],
    'role' => ['super_admin' => '플랫폼 관리자', 'company_owner' => '회사 소유자', 'manager' => '매니저', 'guest' => '투숙객'],
    'status' => ['new' => '신규', 'accepted' => '접수됨', 'in_progress' => '처리 중', 'waiting_guest' => '투숙객 대기', 'completed' => '완료', 'cancelled' => '취소됨'],
    'priority' => ['low' => '낮음', 'normal' => '보통', 'high' => '높음', 'urgent' => '긴급'],
];
