@extends('layouts.workspace')
@section('title','Команда')
@section('content')
<div class="d-flex align-items-end justify-content-between gap-3 mb-4"><div><div class="eyebrow">Доступ к компании</div><h1 class="page-title">Команда</h1><p class="page-subtitle">Владелец управляет менеджерами только своего отеля.</p></div><div class="page-actions"><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newMemberModal"><i class="bi bi-person-plus me-sm-2"></i><span>Добавить менеджера</span></button></div></div>
<div class="surface-card overflow-hidden"><div class="table-responsive"><table class="table"><thead><tr><th>Пользователь</th><th>Роль</th><th>Телефон</th><th>Последний вход</th><th>Доступ</th><th></th></tr></thead><tbody>
@foreach($members as $member)<tr><td><div class="d-flex align-items-center gap-3"><span class="avatar">{{ mb_strtoupper(mb_substr($member->name,0,2)) }}</span><div><div class="fw-semibold small">{{ $member->name }}</div><div class="text-secondary" style="font-size:11px">{{ $member->email }}</div></div></div></td><td><span class="badge text-bg-light border">{{ $member->role->label() }}</span></td><td class="small">{{ $member->phone ?: '—' }}</td><td class="small text-secondary">{{ $member->last_login_at?->diffForHumans() ?? 'Ещё не входил' }}</td><td><span class="badge-soft-{{ $member->is_active ? 'success' : 'secondary' }}">{{ $member->is_active ? 'Активен' : 'Отключён' }}</span><div class="text-secondary mt-1" style="font-size:9px"><i class="bi bi-envelope me-1"></i>{{ $member->email_notifications ? 'Email включён' : 'Email выключен' }}</div></td><td>@if($member->role===\App\Enums\UserRole::Manager)<div class="dropdown"><button class="btn btn-light btn-sm" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></button><div class="dropdown-menu dropdown-menu-end"><button class="dropdown-item edit-member" data-bs-toggle="modal" data-bs-target="#editMemberModal" data-id="{{ $member->id }}" data-name="{{ $member->name }}" data-email="{{ $member->email }}" data-phone="{{ $member->phone }}" data-locale="{{ $member->preferred_locale }}" data-email-notifications="{{ $member->email_notifications ? 1 : 0 }}"><i class="bi bi-pencil me-2"></i>Редактировать</button><form method="POST" action="{{ route('workspace.team.toggle',$member) }}">@csrf @method('PATCH')<button class="dropdown-item {{ $member->is_active ? 'text-danger' : 'text-success' }}"><i class="bi {{ $member->is_active ? 'bi-person-x' : 'bi-person-check' }} me-2"></i>{{ $member->is_active ? 'Отключить' : 'Включить' }}</button></form></div></div>@endif</td></tr>@endforeach
</tbody></table></div></div>
@endsection
@push('modals')
<div class="modal fade" id="newMemberModal"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" action="{{ route('workspace.team.store') }}">@csrf<div class="modal-header"><div><h2 class="modal-title fs-5">Новый менеджер</h2><div class="text-secondary small">Доступ только к {{ $currentCompany->name }}</div></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body p-4"><div class="mb-3"><label class="form-label">Имя *</label><input class="form-control" name="name" required></div><div class="mb-3"><label class="form-label">Email *</label><input class="form-control" type="email" name="email" required></div><div class="mb-3"><label class="form-label">Телефон</label><input class="form-control" name="phone"></div><div class="mb-3"><label class="form-label">Язык писем</label><select class="form-select" name="preferred_locale">@foreach(['ru'=>'Русский','id'=>'Bahasa Indonesia','en'=>'English','uk'=>'Українська','ar'=>'العربية','he'=>'עברית','zh'=>'中文','ko'=>'한국어'] as $code=>$label)<option value="{{ $code }}">{{ $label }}</option>@endforeach</select></div><div class="form-check form-switch mb-3"><input type="hidden" name="email_notifications" value="0"><input class="form-check-input" type="checkbox" name="email_notifications" value="1" id="newMemberEmailNotifications" checked><label class="form-check-label" for="newMemberEmailNotifications">Получать заявки по email</label></div><div class="mb-3"><label class="form-label">Временный пароль *</label><input class="form-control" type="password" name="password" required></div><div><label class="form-label">Повторите пароль *</label><input class="form-control" type="password" name="password_confirmation" required></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Отмена</button><button class="btn btn-primary">Добавить</button></div></form></div></div>
<div class="modal fade" id="editMemberModal"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" action="">@csrf @method('PUT')<div class="modal-header"><h2 class="modal-title fs-5">Редактировать менеджера</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body p-4"><div class="mb-3"><label class="form-label">Имя *</label><input class="form-control edit-name" name="name" required></div><div class="mb-3"><label class="form-label">Email *</label><input class="form-control edit-email" type="email" name="email" required></div><div class="mb-3"><label class="form-label">Телефон</label><input class="form-control edit-phone" name="phone"></div><div class="mb-3"><label class="form-label">Язык писем</label><select class="form-select edit-locale" name="preferred_locale">@foreach(['ru'=>'Русский','id'=>'Bahasa Indonesia','en'=>'English','uk'=>'Українська','ar'=>'العربية','he'=>'עברית','zh'=>'中文','ko'=>'한국어'] as $code=>$label)<option value="{{ $code }}">{{ $label }}</option>@endforeach</select></div><div class="form-check form-switch"><input type="hidden" name="email_notifications" value="0"><input class="form-check-input edit-email-notifications" type="checkbox" name="email_notifications" value="1" id="editMemberEmailNotifications"><label class="form-check-label" for="editMemberEmailNotifications">Получать заявки по email</label></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Отмена</button><button class="btn btn-primary">Сохранить</button></div></form></div></div>
@endpush
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>document.querySelectorAll('.edit-member').forEach(btn=>btn.addEventListener('click',()=>{const modal=document.getElementById('editMemberModal');modal.querySelector('form').action='/workspace/team/'+btn.dataset.id;modal.querySelector('.edit-name').value=btn.dataset.name;modal.querySelector('.edit-email').value=btn.dataset.email;modal.querySelector('.edit-phone').value=btn.dataset.phone||'';modal.querySelector('.edit-locale').value=btn.dataset.locale||'ru';modal.querySelector('.edit-email-notifications').checked=btn.dataset.emailNotifications==='1';})));</script>@endpush
