<div class="row g-3">
    <div class="col-md-4"><label class="form-label">{{ __('workspace.type') }} *</label><select class="form-select node-type-select" name="type" required><option value="category">{{ __('workspace.category') }}</option><option value="service">{{ __('workspace.service_type') }}</option><option value="guide">{{ __('workspace.guide_type') }}</option></select></div>
    <div class="col-md-8"><label class="form-label">{{ __('workspace.name') }} *</label><input class="form-control node-name" name="name" required placeholder="{{ __('workspace.name_hint') }}"></div>
    <div class="col-md-8"><label class="form-label">{{ __('workspace.parent_category') }}</label><select class="form-select node-parent" name="parent_id"><option value="">{{ __('workspace.root_level') }}</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->localizedName() }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">{{ __('workspace.icon') }}</label><input class="form-control node-icon" name="icon" value="bi-stars" placeholder="bi-stars"></div>
    <div class="col-12"><label class="form-label">{{ __('workspace.description') }} · Русский</label><textarea class="form-control node-description" name="description" rows="6" maxlength="3000" placeholder="{{ __('workspace.description_hint') }}"></textarea></div>
    <div class="col-12"><div class="translation-editor"><div class="d-flex align-items-start justify-content-between gap-3 mb-3"><div><label class="form-label mb-1">{{ __('workspace.translations') }}</label><div class="form-hint">{{ __('workspace.translations_hint') }}</div></div><span class="badge text-bg-light border">7</span></div><div class="accordion accordion-flush translation-accordion">
        @foreach(['en'=>'English','id'=>'Bahasa Indonesia','uk'=>'Українська','ar'=>'العربية','he'=>'עברית','zh'=>'中文','ko'=>'한국어'] as $locale=>$language)
        <div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed py-2" type="button" data-bs-toggle="collapse" data-bs-target="#translation-{{ $locale }}-{{ $translationScope ?? 'form' }}">{{ $language }} <small class="ms-2 text-secondary">{{ mb_strtoupper($locale) }}</small></button></h3><div class="accordion-collapse collapse" id="translation-{{ $locale }}-{{ $translationScope ?? 'form' }}"><div class="accordion-body px-0"><div class="row g-2"><div class="col-md-5"><label class="form-label">{{ __('workspace.localized_name') }}</label><input class="form-control node-translation-name" data-locale="{{ $locale }}" name="translations[{{ $locale }}][name]" maxlength="160"></div><div class="col-md-7"><label class="form-label">{{ __('workspace.localized_text') }}</label><textarea class="form-control node-translation-description" data-locale="{{ $locale }}" name="translations[{{ $locale }}][description]" rows="5" maxlength="4000"></textarea></div></div></div></div></div>
        @endforeach
    </div></div></div>
    <div class="node-service-fields col-12"><div class="row g-3"><div class="col-md-6"><label class="form-label">{{ __('workspace.base_price',['currency'=>$currentCompany->currency]) }}</label><div class="input-group"><input class="form-control node-price" type="number" min="0" step="{{ $currentCompany->currency === 'IDR' ? 1 : '.01' }}" name="price" placeholder="{{ __('workspace.free_price_hint') }}"><span class="input-group-text">{{ $currentCompany->currency }}</span></div><div class="form-hint mt-1">{{ __('workspace.usd_hint') }}</div></div><div class="col-md-6"><label class="form-label">{{ __('workspace.sla_minutes') }}</label><input class="form-control node-sla" type="number" min="1" name="sla_minutes" placeholder="20"></div>
        <div class="col-12"><div class="service-option-editor"><div><label class="form-label mb-1">{{ __('workspace.guest_service_options') }}</label><p>{{ __('workspace.guest_service_options_hint') }}</p></div><div class="service-option-grid">@foreach($serviceOptions as $optionKey=>$optionIcon)<label><input class="node-option" type="checkbox" name="option_keys[]" value="{{ $optionKey }}"><span><i class="bi {{ $optionIcon }}"></i><b>{{ __('workspace.service_options.'.$optionKey) }}</b><i class="bi bi-check-circle-fill"></i></span></label>@endforeach</div></div></div>
    </div></div>
    <div class="col-12"><div class="d-flex align-items-center justify-content-between mb-2"><label class="form-label mb-0">{{ __('workspace.background') }}</label><a class="form-hint" href="{{ route('workspace.backgrounds.index') }}">{{ __('workspace.manage_backgrounds') }} <i class="bi bi-arrow-up-right"></i></a></div><div class="service-bg-picker"><label><input class="node-background" type="radio" name="background_image_id" value="" checked><span class="background-inherit"><b>{{ __('workspace.inherit_background') }}</b><i class="bi bi-check-circle-fill"></i></span></label>@foreach($backgroundImages as $image)<label><input class="node-background" type="radio" name="background_image_id" value="{{ $image->id }}"><span style="background-image:url('{{ $image->url() }}');background-position:{{ $image->background_position }};background-size:{{ $image->background_size }}"><b>{{ $image->name }}</b><i class="bi bi-check-circle-fill"></i></span></label>@endforeach</div></div>
    <div class="col-md-6"><label class="form-label">{{ __('workspace.sort_order') }}</label><input class="form-control node-order" type="number" min="0" name="sort_order" value="0"></div>
    <div class="col-md-6 d-flex align-items-end pb-2"><div class="form-check form-switch"><input type="hidden" name="is_active" value="0"><input class="form-check-input node-active" type="checkbox" name="is_active" value="1" checked><label class="form-check-label small fw-semibold">{{ __('workspace.show_guests') }}</label></div></div>
</div>
