<li class="service-tree-item">
    <div class="service-node-row {{ !$node->is_active ? 'is-muted' : '' }}" style="--tree-level:{{ $level }}">
        <div class="service-node-line"></div>
        <button class="tree-toggle" type="button" @if($node->children->isNotEmpty()) data-bs-toggle="collapse" data-bs-target="#children-{{ $node->id }}" @else disabled @endif><i class="bi {{ $node->children->isNotEmpty() ? 'bi-chevron-down' : 'bi-dot' }}"></i></button>
        <span class="service-node-icon {{ $node->isCategory() ? 'category' : ($node->isGuide() ? 'guide' : 'service') }}" @if($node->backgroundImage) style="background-image:linear-gradient(rgba(16,42,46,.52),rgba(16,42,46,.52)),url('{{ $node->backgroundImage->url() }}');background-position:{{ $node->backgroundImage->background_position }};background-size:{{ $node->backgroundImage->background_size }};color:#fff" @endif><i class="bi {{ $node->icon ?: ($node->isCategory() ? 'bi-folder2' : 'bi-stars') }}"></i></span>
        <div class="flex-grow-1 min-w-0"><div class="d-flex align-items-center gap-2"><span class="fw-semibold text-truncate">{{ $node->localizedName() }}</span><span class="node-type">{{ __('workspace.'.($node->isCategory() ? 'category' : ($node->isGuide() ? 'guide_type' : 'service_type'))) }}</span>@if($node->option_keys)<span class="node-feature-badge"><i class="bi bi-ui-checks"></i>{{ count($node->option_keys) }}</span>@endif @if($node->smart_home_enabled)<span class="node-feature-badge smart"><i class="bi bi-house-gear"></i>{{ __('workspace.demo') }}</span>@endif @unless($node->is_active)<span class="badge text-bg-light border">{{ __('workspace.hidden') }}</span>@endunless</div><div class="text-secondary text-truncate" style="font-size:11px">{{ $node->localizedDescription() ?: ($node->isCategory() ? __('workspace.nested_items',['count'=>$node->children->count()]) : __('workspace.no_description')) }}</div></div>
        @if($node->type === \App\Enums\ServiceNodeType::Service)<div class="node-meta d-none d-md-flex"><span><i class="bi bi-clock me-1"></i>{{ $node->sla_minutes ? __('workspace.minutes',['count'=>$node->sla_minutes]) : __('workspace.no_sla') }}</span><strong>{{ $node->price_minor !== null ? app(\App\Support\Money::class)->format($node->price_minor,$currentCompany->currency) : __('workspace.free') }}</strong></div>@endif
        <div class="dropdown"><button class="btn btn-light btn-sm" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></button><div class="dropdown-menu dropdown-menu-end"><button class="dropdown-item edit-service-node" type="button" data-bs-toggle="modal" data-bs-target="#editNodeModal" data-id="{{ $node->id }}" data-name="{{ $node->name }}" data-type="{{ $node->type->value }}" data-parent="{{ $node->parent_id }}" data-description="{{ $node->description }}" data-icon="{{ $node->icon }}" data-background-image="{{ $node->background_image_id }}" data-price="{{ $node->price_minor === null ? '' : ($currentCompany->currency === 'IDR' ? $node->price_minor : $node->price_minor/100) }}" data-sla="{{ $node->sla_minutes }}" data-order="{{ $node->sort_order }}" data-active="{{ $node->is_active ? 1 : 0 }}"><i class="bi bi-pencil me-2"></i>{{ __('workspace.edit') }}</button>@if($node->isCategory())<button class="dropdown-item add-child-node" type="button" data-bs-toggle="modal" data-bs-target="#addNodeModal" data-parent="{{ $node->id }}"><i class="bi bi-plus-lg me-2"></i>{{ __('workspace.add_inside') }}</button>@endif<div class="dropdown-divider"></div><form method="POST" action="{{ route('workspace.services.destroy',$node) }}" onsubmit="return confirm('{{ __('workspace.delete_confirm') }}')">@csrf @method('DELETE')<button class="dropdown-item text-danger"><i class="bi bi-trash me-2"></i>{{ __('workspace.delete') }}</button></form></div></div>
    </div>
    @if($node->children->isNotEmpty())<ul class="service-tree collapse show" id="children-{{ $node->id }}">@foreach($node->children as $child)@include('workspace.services._node',['node'=>$child,'level'=>$level+1])@endforeach</ul>@endif
</li>
