@extends('layouts.admin')
@section('title', 'Редактировать пользователя')
@section('content')
<div class="d-flex align-items-end justify-content-between gap-3 mb-4"><div><a class="text-secondary small" href="{{ route('platform.users.index') }}"><i class="bi bi-arrow-left me-1"></i>Пользователи</a><div class="eyebrow mt-3">Системный аккаунт</div><h1 class="page-title">{{ $user->name }}</h1><p class="page-subtitle">Изменения доступа применяются при следующем запросе пользователя.</p></div><div class="d-flex align-items-center gap-2">@if($user->is_active && $user->company_id && !$user->isSuperAdmin())<form method="POST" action="{{ route('platform.users.impersonate',$user) }}" onsubmit="return confirm('Войти в кабинет этого пользователя?')">@csrf<button class="btn btn-primary"><i class="bi bi-box-arrow-in-right me-2"></i>Войти как пользователь</button></form>@endif<span class="avatar" style="width:54px;height:54px;font-size:16px">{{ mb_strtoupper(mb_substr($user->name,0,2)) }}</span></div></div>

<form method="POST" action="{{ route('platform.users.update',$user) }}">@csrf @method('PUT')
<div class="row g-3"><div class="col-xl-8"><div class="surface-card overflow-hidden">
<section class="form-section"><div class="form-section-title">Основные данные</div><div class="form-section-copy">Имя и контакты пользователя для входа и связи.</div><div class="row g-3"><div class="col-md-6"><label class="form-label">Имя *</label><input class="form-control" name="name" value="{{ old('name',$user->name) }}" required></div><div class="col-md-6"><label class="form-label">Email *</label><input class="form-control" type="email" name="email" value="{{ old('email',$user->email) }}" required></div><div class="col-md-6"><label class="form-label">Телефон</label><input class="form-control" name="phone" value="{{ old('phone',$user->phone) }}"></div></div></section>
<section class="form-section"><div class="form-section-title">Email-уведомления</div><div class="form-section-copy">Новые заявки и изменения будут приходить на email пользователя.</div><div class="row g-3"><div class="col-md-6"><label class="form-label">Язык писем</label><select class="form-select" name="preferred_locale">@foreach(['ru'=>'Русский','id'=>'Bahasa Indonesia','en'=>'English','uk'=>'Українська','ar'=>'العربية','he'=>'עברית','zh'=>'中文','ko'=>'한국어'] as $code=>$label)<option value="{{ $code }}" @selected(old('preferred_locale',$user->preferred_locale)===$code)>{{ $label }}</option>@endforeach</select></div><div class="col-md-6 d-flex align-items-end"><div class="form-check form-switch mb-2"><input type="hidden" name="email_notifications" value="0"><input class="form-check-input" type="checkbox" name="email_notifications" value="1" id="systemUserEmailNotifications" @checked((bool)old('email_notifications',$user->email_notifications))><label class="form-check-label" for="systemUserEmailNotifications">Получать уведомления</label></div></div></div></section>
<section class="form-section"><div class="form-section-title">Новый пароль</div><div class="form-section-copy">Оставьте поля пустыми, если пароль менять не нужно.</div><div class="row g-3"><div class="col-md-6"><label class="form-label">Новый пароль</label><input class="form-control" type="password" name="password" minlength="8" autocomplete="new-password"></div><div class="col-md-6"><label class="form-label">Повторите пароль</label><input class="form-control" type="password" name="password_confirmation" minlength="8" autocomplete="new-password"></div></div></section>
</div></div>
<div class="col-xl-4"><div class="surface-card p-4"><h2 class="section-title">Роль и доступ</h2><p class="text-secondary small mt-2">Определяет доступный раздел и данные компании.</p><div class="mt-4"><label class="form-label">Роль *</label><select class="form-select" id="systemUserRole" name="role" required>@foreach([\App\Enums\UserRole::SuperAdmin,\App\Enums\UserRole::CompanyOwner,\App\Enums\UserRole::Manager] as $role)<option value="{{ $role->value }}" @selected(old('role',$user->role->value)===$role->value)>{{ $role->label() }}</option>@endforeach</select></div><div class="mt-3" id="systemUserCompany"><label class="form-label">Компания</label><select class="form-select" name="company_id"><option value="">Выберите компанию</option>@foreach($companies as $company)<option value="{{ $company->id }}" @selected((int)old('company_id',$user->company_id)===$company->id)>{{ $company->name }}</option>@endforeach</select></div><div class="form-check form-switch mt-4"><input type="hidden" name="is_active" value="0"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="systemUserActive" @checked((bool)old('is_active',$user->is_active))><label class="form-check-label fw-semibold small" for="systemUserActive">Доступ включён</label></div>@if($user->role===\App\Enums\UserRole::CompanyOwner)<div class="alert alert-light border mt-4 mb-0"><i class="bi bi-shield-check me-1"></i> Компания должна сохранять хотя бы одного владельца.</div>@endif</div><div class="d-grid gap-2 mt-3"><button class="btn btn-primary">Сохранить изменения</button><a class="btn btn-light" href="{{ route('platform.users.index') }}">Отмена</a></div></div></div>
</form>
@endsection
@push('scripts')
<script>document.addEventListener('DOMContentLoaded',()=>{const role=document.getElementById('systemUserRole'),company=document.getElementById('systemUserCompany');const toggle=()=>company.classList.toggle('d-none',role.value==='super_admin');role.addEventListener('change',toggle);toggle();});</script>
@endpush
