@extends('layouts.admin')
@section('title', 'Пользователи')
@section('content')
<div class="d-flex align-items-end justify-content-between gap-3 mb-4"><div><div class="eyebrow">Доступ к системе</div><h1 class="page-title">Пользователи</h1><p class="page-subtitle">Все администраторы, владельцы и менеджеры платформы.</p></div><span class="badge text-bg-light border">{{ $users->total() }} аккаунтов</span></div>

<div class="surface-card overflow-hidden">
<form class="p-3 p-md-4 border-bottom" method="GET"><div class="row g-2"><div class="col-lg"><div class="search-box"><i class="bi bi-search"></i><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Имя, email, телефон или компания"></div></div><div class="col-sm-6 col-lg-auto"><select class="form-select" name="role"><option value="">Все роли</option>@foreach([\App\Enums\UserRole::SuperAdmin,\App\Enums\UserRole::CompanyOwner,\App\Enums\UserRole::Manager] as $role)<option value="{{ $role->value }}" @selected(request('role')===$role->value)>{{ $role->label() }}</option>@endforeach</select></div><div class="col-sm-6 col-lg-auto"><select class="form-select" name="company_id"><option value="">Все компании</option>@foreach($companies as $company)<option value="{{ $company->id }}" @selected((int)request('company_id')===$company->id)>{{ $company->name }}</option>@endforeach</select></div><div class="col-sm-6 col-lg-auto"><select class="form-select" name="active"><option value="">Любой доступ</option><option value="1" @selected(request('active')==='1')>Активные</option><option value="0" @selected(request('active')==='0')>Отключённые</option></select></div><div class="col-sm-6 col-lg-auto"><button class="btn btn-light h-100 px-3">Применить</button></div></div></form>

<div class="table-responsive"><table class="table"><thead><tr><th>Пользователь</th><th>Роль</th><th>Компания</th><th>Телефон</th><th>Последний вход</th><th>Доступ</th><th></th></tr></thead><tbody>
@forelse($users as $user)
<tr><td><div class="d-flex align-items-center gap-3"><span class="avatar">{{ mb_strtoupper(mb_substr($user->name,0,2)) }}</span><div><div class="fw-semibold small">{{ $user->name }} @if(auth()->id()===$user->id)<span class="text-secondary">· вы</span>@endif</div><div class="text-secondary" style="font-size:11px">{{ $user->email }}</div></div></div></td><td><span class="badge text-bg-light border">{{ $user->role->label() }}</span></td><td><div class="small fw-semibold">{{ $user->company?->name ?? 'Luma Platform' }}</div></td><td class="small">{{ $user->phone ?: '—' }}</td><td class="small text-secondary">{{ $user->last_login_at?->diffForHumans() ?? 'Ещё не входил' }}</td><td><span class="badge-soft-{{ $user->is_active ? 'success' : 'secondary' }}">{{ $user->is_active ? 'Активен' : 'Отключён' }}</span></td><td><div class="d-flex gap-1 justify-content-end">@if($user->is_active && $user->company_id && !$user->isSuperAdmin())<form method="POST" action="{{ route('platform.users.impersonate',$user) }}" onsubmit="return confirm('Войти в кабинет этого пользователя?')">@csrf<button class="btn btn-primary btn-sm" title="Войти как пользователь" aria-label="Войти как пользователь"><i class="bi bi-box-arrow-in-right"></i></button></form>@endif<a class="btn btn-light btn-sm" href="{{ route('platform.users.edit',$user) }}" title="Редактировать" aria-label="Редактировать"><i class="bi bi-pencil"></i></a></div></td></tr>
@empty<tr><td colspan="7" class="text-center py-5"><i class="bi bi-people fs-2 text-secondary"></i><div class="fw-semibold mt-2">Пользователи не найдены</div><div class="text-secondary small">Измените параметры поиска.</div></td></tr>@endforelse
</tbody></table></div>
@if($users->hasPages())<div class="p-3 border-top">{{ $users->links() }}</div>@endif
</div>
@endsection
