<section class="guest-form-card smart-home-panel" data-smart-home data-storage-key="luma-smart-home-{{ $company->id }}-{{ app('guestStay')->guest_stay_id }}">
    <div class="smart-home-heading"><div><span class="eyebrow">{{ __('guest.smart_home_eyebrow') }}</span><h2>{{ __('guest.smart_home_title') }}</h2><p>{{ __('guest.smart_home_intro') }}</p></div><span class="smart-demo-badge"><i class="bi bi-broadcast-pin"></i>{{ __('guest.demo_mode') }}</span></div>
    <div class="smart-home-scenes">
        @foreach(['welcome'=>'bi-door-open','relax'=>'bi-cup-hot','sleep'=>'bi-moon-stars','away'=>'bi-lock'] as $scene=>$icon)<button type="button" data-smart-scene="{{ $scene }}"><i class="bi {{ $icon }}"></i><span>{{ __('guest.smart_scene_'.$scene) }}</span></button>@endforeach
    </div>
    <div class="smart-home-grid">
        <article class="smart-control-card wide"><div class="smart-control-title"><span><i class="bi bi-lightbulb"></i></span><div><strong>{{ __('guest.smart_lighting') }}</strong><small>{{ __('guest.smart_lighting_hint') }}</small></div></div><div class="smart-toggle-row"><label><span>{{ __('guest.smart_main_light') }}</span><input type="checkbox" data-smart-key="mainLight" checked><i></i></label><label><span>{{ __('guest.smart_bedside_light') }}</span><input type="checkbox" data-smart-key="bedsideLight" checked><i></i></label></div><label class="smart-range"><span>{{ __('guest.smart_brightness') }} <b data-smart-output="brightness">70%</b></span><input type="range" min="0" max="100" step="5" value="70" data-smart-key="brightness"></label></article>
        <article class="smart-control-card"><div class="smart-control-title"><span><i class="bi bi-window"></i></span><div><strong>{{ __('guest.smart_curtains') }}</strong><small>{{ __('guest.smart_curtains_hint') }}</small></div></div><div class="smart-segmented">@foreach(['open','half','closed'] as $position)<label><input type="radio" name="smart_curtains" value="{{ $position }}" data-smart-key="curtains" @checked($position==='open')><span>{{ __('guest.smart_curtains_'.$position) }}</span></label>@endforeach</div></article>
        <article class="smart-control-card"><div class="smart-control-title"><span><i class="bi bi-thermometer-half"></i></span><div><strong>{{ __('guest.smart_climate') }}</strong><small>{{ __('guest.smart_climate_hint') }}</small></div></div><label class="smart-power"><span>{{ __('guest.smart_climate_power') }}</span><input type="checkbox" data-smart-key="climate" checked><i></i></label><label class="smart-range"><span>{{ __('guest.smart_temperature') }} <b data-smart-output="temperature">23°C</b></span><input type="range" min="16" max="30" step="1" value="23" data-smart-key="temperature"></label></article>
        <article class="smart-control-card wide"><div class="smart-control-title"><span><i class="bi bi-shield-check"></i></span><div><strong>{{ __('guest.smart_privacy') }}</strong><small>{{ __('guest.smart_privacy_hint') }}</small></div></div><div class="smart-toggle-row"><label><span>{{ __('guest.smart_do_not_disturb') }}</span><input type="checkbox" data-smart-key="doNotDisturb"><i></i></label><label><span>{{ __('guest.smart_night_light') }}</span><input type="checkbox" data-smart-key="nightLight"><i></i></label></div></article>
    </div>
    <div class="smart-home-feedback"><i class="bi bi-check2-circle"></i><span data-smart-feedback>{{ __('guest.smart_home_ready') }}</span></div>
</section>

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-smart-home]').forEach(panel=>{const defaults={mainLight:true,bedsideLight:true,brightness:70,curtains:'open',climate:true,temperature:23,doNotDisturb:false,nightLight:false};let state={...defaults};try{state={...state,...JSON.parse(localStorage.getItem(panel.dataset.storageKey)||'{}')}}catch(e){}const feedback=panel.querySelector('[data-smart-feedback]');const sync=()=>{panel.querySelectorAll('[data-smart-key]').forEach(input=>{const key=input.dataset.smartKey;if(input.type==='radio')input.checked=state[key]===input.value;else if(input.type==='checkbox')input.checked=Boolean(state[key]);else input.value=state[key];});panel.querySelector('[data-smart-output="brightness"]').textContent=state.brightness+'%';panel.querySelector('[data-smart-output="temperature"]').textContent=state.temperature+'°C';try{localStorage.setItem(panel.dataset.storageKey,JSON.stringify(state))}catch(e){}};const changed=message=>{feedback.textContent=message;panel.querySelector('.smart-home-feedback').classList.add('is-saved');setTimeout(()=>panel.querySelector('.smart-home-feedback').classList.remove('is-saved'),900);sync();};panel.addEventListener('change',event=>{const input=event.target.closest('[data-smart-key]');if(!input)return;state[input.dataset.smartKey]=input.type==='checkbox'?input.checked:(input.type==='range'?Number(input.value):input.value);changed(@json(__('guest.smart_home_saved')));});panel.addEventListener('input',event=>{const input=event.target.closest('input[type="range"][data-smart-key]');if(!input)return;state[input.dataset.smartKey]=Number(input.value);sync();});panel.addEventListener('click',event=>{const button=event.target.closest('[data-smart-scene]');if(!button)return;const scenes={welcome:{mainLight:true,bedsideLight:true,brightness:85,curtains:'open',climate:true,temperature:23,doNotDisturb:false,nightLight:false},relax:{mainLight:true,bedsideLight:true,brightness:35,curtains:'half',climate:true,temperature:23,doNotDisturb:false,nightLight:false},sleep:{mainLight:false,bedsideLight:false,brightness:0,curtains:'closed',climate:true,temperature:22,doNotDisturb:true,nightLight:true},away:{mainLight:false,bedsideLight:false,brightness:0,curtains:'closed',climate:false,temperature:24,doNotDisturb:true,nightLight:false}};state={...state,...scenes[button.dataset.smartScene]};panel.querySelectorAll('[data-smart-scene]').forEach(item=>item.classList.toggle('active',item===button));changed(@json(__('guest.smart_scene_applied')));});sync();});});
</script>
@endpush
