@extends('layouts.guest')
@section('title', __('guest.status_title'))
@section('content')
@php $money = app(\App\Support\Money::class); @endphp
<div class="guest-page-heading"><a href="{{ route('guest.orders.index', $company) }}"><i class="bi bi-arrow-left"></i></a><div><span class="eyebrow">{{ __('guest.order_number', ['number'=>str($serviceRequest->public_id)->substr(0, 8)->upper()]) }}</span><h1>{{ __('guest.status_title') }}</h1></div></div>
<section class="guest-order-hero status-{{ $serviceRequest->status->value }}"><span class="order-hero-icon"><i class="bi {{ $serviceRequest->status === \App\Enums\RequestStatus::Completed ? 'bi-check-lg' : ($serviceRequest->status === \App\Enums\RequestStatus::Cancelled ? 'bi-x-lg' : 'bi-bell') }}"></i></span><span class="eyebrow">{{ __('guest.current_status') }}</span><h2>{{ __('guest.status.'.$serviceRequest->status->value) }}</h2><p>@switch($serviceRequest->status)@case(\App\Enums\RequestStatus::New){{ __('guest.team_received') }}@break @case(\App\Enums\RequestStatus::Accepted){{ __('guest.accepted_hint') }}@break @case(\App\Enums\RequestStatus::InProgress){{ __('guest.progress_hint') }}@break @case(\App\Enums\RequestStatus::WaitingGuest){{ __('guest.waiting_hint') }}@break @case(\App\Enums\RequestStatus::Completed){{ __('guest.completed_hint') }}@break @default {{ __('guest.cancelled_hint') }} @endswitch</p></section>
<div class="guest-order-detail-grid"><section class="guest-form-card"><div class="guest-card-heading"><span><i class="bi bi-bag-check"></i></span><div><h2>{{ __('guest.order_contents') }}</h2><p>{{ __('guest.created_at', ['date'=>$serviceRequest->created_at->format('d.m.Y · H:i')]) }}</p></div></div><div class="checkout-lines">@foreach($serviceRequest->items as $item)<div><span>{{ $item->service?->localizedName() ?? $item->name }} <small>× {{ $item->quantity }}</small>@if($item->notes)<em>{{ $item->notes }}</em>@endif</span><strong>@if($item->total_minor){{ $money->format($item->total_minor, $company->currency) }}@else{{ __('guest.free') }}@endif</strong></div>@endforeach</div><div class="checkout-total"><span>{{ __('guest.total') }}</span><div><strong>@if($serviceRequest->price_minor){{ $money->format($serviceRequest->price_minor, $company->currency) }}@else{{ __('guest.free') }}@endif</strong>@if($serviceRequest->price_minor && $money->approximateUsd($serviceRequest->price_minor, $company->currency))<small>{{ $money->approximateUsd($serviceRequest->price_minor, $company->currency) }}</small>@endif</div></div>@if($serviceRequest->price_minor)<div class="payment-caption"><i class="bi {{ $serviceRequest->payment_method === 'cash' ? 'bi-check-circle-fill' : 'bi-door-open' }}"></i><span><small>{{ $serviceRequest->payment_method === 'cash' ? __('guest.cash_paid') : __('guest.payment_method') }}</small><strong>{{ $serviceRequest->payment_method === 'cash' ? __('guest.cash') : __('guest.room_charge') }}</strong></span></div>@endif</section>
<section class="guest-form-card guest-progress-card"><div class="guest-card-heading"><span><i class="bi bi-activity"></i></span><div><h2>{{ __('guest.progress') }}</h2><p>{{ __('guest.updated_by_team') }}</p></div></div><div class="guest-timeline">@foreach($serviceRequest->history->sortBy('created_at') as $event)@php $eventStatus = \App\Enums\RequestStatus::tryFrom($event->to_status); @endphp<div class="guest-timeline-row"><span></span><div><strong>{{ $eventStatus ? __('guest.status.'.$eventStatus->value) : __('guest.progress') }}</strong><small>{{ $event->created_at->format('d.m · H:i') }}</small>@if($event->note)<p>{{ $event->note === 'Заказ создан гостем через каталог' ? __('guest.created_via_catalog') : $event->note }}</p>@endif</div></div>@endforeach</div></section></div>
<div class="guest-help-note"><i class="bi bi-telephone-x"></i><span><strong>{{ __('guest.calls_unavailable_title') }}</strong><small>{{ __('guest.calls_unavailable') }}</small></span></div>
@endsection
@push('scripts')<script>setTimeout(() => window.location.reload(), 30000);</script>@endpush
