@extends('layouts.guest')
@section('title', __('guest.status_title'))
@section('content')
@php $money = app(\App\Support\Money::class); @endphp
<div class="guest-page-heading" data-order-status-poller data-order-id="{{ $serviceRequest->public_id }}" data-order-status="{{ $serviceRequest->status->value }}" data-payment-status="{{ $serviceRequest->payment_status }}" data-updated-message="{{ __('guest.orders_updated') }}" data-current-message="{{ __('guest.orders_up_to_date') }}" data-error-message="{{ __('guest.refresh_failed') }}"><a href="{{ route('guest.orders.index', $company) }}"><i class="bi bi-arrow-left"></i></a><div><span class="eyebrow">{{ __('guest.order_number', ['number'=>str($serviceRequest->public_id)->substr(0, 8)->upper()]) }}</span><h1>{{ __('guest.status_title') }}</h1></div></div>
<section class="guest-order-hero status-{{ $serviceRequest->status->value }}" data-order-hero><span class="order-hero-icon"><i class="bi {{ in_array($serviceRequest->status, [\App\Enums\RequestStatus::Ready, \App\Enums\RequestStatus::Completed], true) ? 'bi-check-lg' : ($serviceRequest->status === \App\Enums\RequestStatus::Cancelled ? 'bi-x-lg' : 'bi-bell') }}"></i></span><span class="eyebrow">{{ __('guest.current_status') }}</span><h2>{{ __('guest.status.'.$serviceRequest->status->value) }}</h2><p>@switch($serviceRequest->status)@case(\App\Enums\RequestStatus::New){{ __('guest.team_received') }}@break @case(\App\Enums\RequestStatus::Accepted){{ __('guest.accepted_hint') }}@break @case(\App\Enums\RequestStatus::InProgress){{ __('guest.progress_hint') }}@break @case(\App\Enums\RequestStatus::WaitingGuest){{ __('guest.waiting_hint') }}@break @case(\App\Enums\RequestStatus::Ready){{ __('guest.ready_hint') }}@break @case(\App\Enums\RequestStatus::Completed){{ __('guest.completed_hint') }}@break @default {{ __('guest.cancelled_hint') }} @endswitch</p></section>
<div data-order-detail-progress>@include('guest.orders._progress', ['order' => $serviceRequest])</div>
<section class="guest-confirm-card" data-order-confirm @if(!in_array($serviceRequest->status, [\App\Enums\RequestStatus::Ready, \App\Enums\RequestStatus::WaitingGuest], true)) hidden @endif><span><i class="bi bi-person-check"></i></span><div><h2>{{ __('guest.confirm_title') }}</h2><p>{{ $serviceRequest->payment_method === 'room_charge' && $serviceRequest->price_minor > 0 ? __('guest.confirm_bill_hint') : __('guest.confirm_hint') }}</p><form method="POST" action="{{ route('guest.orders.confirm', [$company, $serviceRequest]) }}">@csrf<button class="guest-primary-button" type="submit">{{ __('guest.confirm_order') }} <i class="bi bi-check2-circle"></i></button></form></div></section>
@if(in_array($serviceRequest->status,[\App\Enums\RequestStatus::New,\App\Enums\RequestStatus::Accepted],true))<section class="guest-confirm-card"><span><i class="bi bi-x-circle"></i></span><div><h2>{{ __('guest.cancel_order_title') }}</h2><p>{{ __('guest.cancel_order_hint') }}</p><form method="POST" action="{{ route('guest.orders.cancel',[$company,$serviceRequest]) }}" onsubmit="return confirm('{{ __('guest.cancel_order_confirm') }}')">@csrf<button class="guest-primary-button" type="submit">{{ __('guest.cancel_order') }}</button></form></div></section>@endif
@if(in_array($serviceRequest->status,[\App\Enums\RequestStatus::InProgress,\App\Enums\RequestStatus::WaitingGuest,\App\Enums\RequestStatus::Ready],true) && !$serviceRequest->clarification_requested_at)<section class="guest-confirm-card"><span><i class="bi bi-exclamation-triangle"></i></span><div><h2>{{ __('guest.need_clarification_title') }}</h2><p>{{ __('guest.need_clarification_hint') }}</p><form method="POST" action="{{ route('guest.orders.clarification',[$company,$serviceRequest]) }}">@csrf<button class="guest-primary-button" type="submit">{{ __('guest.request_clarification') }}</button></form></div></section>@endif
@if(in_array($serviceRequest->status,[\App\Enums\RequestStatus::Ready,\App\Enums\RequestStatus::Completed],true) && $serviceRequest->price_minor>0 && !$serviceRequest->hasRefund())<section class="guest-confirm-card"><span><i class="bi bi-arrow-counterclockwise"></i></span><div><h2>{{ __('guest.refund_title') }}</h2><p>{{ __('guest.refund_hint') }}</p><form class="d-flex gap-2 flex-wrap" method="POST" action="{{ route('guest.orders.refund',[$company,$serviceRequest]) }}">@csrf<button class="guest-primary-button" name="refund_type" value="partial" type="submit">{{ __('guest.partial_refund') }}</button><button class="guest-primary-button" name="refund_type" value="full" type="submit">{{ __('guest.full_refund') }}</button></form></div></section>@elseif($serviceRequest->hasRefund())<section class="guest-confirm-card"><span><i class="bi bi-arrow-counterclockwise"></i></span><div><h2>{{ __('guest.refund_status_title') }}</h2><p>{{ __('guest.refund_status.'.$serviceRequest->refund_status) }}</p></div></section>@endif
<a class="guest-bill-link" data-order-bill href="{{ route('guest.bill', $company) }}" @if(!($serviceRequest->status === \App\Enums\RequestStatus::Completed && $serviceRequest->payment_status === 'invoiced')) hidden @endif><span><i class="bi bi-receipt"></i></span><div><strong>{{ __('guest.open_bill') }}</strong><small>{{ __('guest.charge_added_to_bill') }}</small></div><i class="bi bi-chevron-right"></i></a>
<div class="guest-order-detail-grid"><section class="guest-form-card"><div class="guest-card-heading"><span><i class="bi bi-bag-check"></i></span><div><h2>{{ __('guest.order_contents') }}</h2><p>{{ __('guest.created_at', ['date'=>$serviceRequest->created_at->format('d.m.Y · H:i')]) }}</p></div></div><div class="checkout-lines">@foreach($serviceRequest->items as $item)<div><span>{{ $item->service?->localizedName() ?? $item->name }} <small>× {{ $item->quantity }}</small>@if($item->options_snapshot)<span class="selected-service-options">@foreach($item->options_snapshot as $optionKey)<b><i class="bi {{ \App\Support\ServiceOptionCatalog::icon($optionKey) }}"></i>{{ __('guest.service_options.'.$optionKey) }}</b>@endforeach</span>@endif @if($item->notes)<em>{{ $item->notes }}</em>@endif</span><strong>@if($item->total_minor){{ $money->format($item->total_minor, $company->currency) }}@else{{ __('guest.free') }}@endif</strong></div>@endforeach</div><div class="checkout-total"><span>{{ __('guest.total') }}</span><div><strong>@if($serviceRequest->price_minor){{ $money->format($serviceRequest->price_minor, $company->currency) }}@else{{ __('guest.free') }}@endif</strong>@if($serviceRequest->price_minor && $money->approximateUsd($serviceRequest->price_minor, $company->currency))<small>{{ $money->approximateUsd($serviceRequest->price_minor, $company->currency) }}</small>@endif</div></div>@if($serviceRequest->price_minor)<div class="payment-caption"><i class="bi {{ $serviceRequest->payment_method === 'cash' ? 'bi-check-circle-fill' : 'bi-credit-card' }}"></i><span><small>{{ $serviceRequest->payment_method === 'cash' ? __('guest.cash_paid') : __('guest.payment_method') }}</small><strong>{{ __('guest.payment_options.'.($serviceRequest->payment_method ?: 'room_charge')) }}</strong></span></div>@endif</section>
<section class="guest-form-card guest-progress-card"><div class="guest-card-heading"><span><i class="bi bi-activity"></i></span><div><h2>{{ __('guest.status_history') }}</h2><p>{{ __('guest.updated_by_team') }}</p></div></div><div class="guest-timeline">@foreach($serviceRequest->history->sortBy('created_at') as $event)@php $eventStatus = \App\Enums\RequestStatus::tryFrom($event->to_status); @endphp<div class="guest-timeline-row"><span></span><div><strong>{{ $eventStatus ? __('guest.status.'.$eventStatus->value) : __('guest.progress') }}</strong><small>{{ $event->created_at->format('d.m · H:i') }}</small>@if($event->note)<p>{{ str_starts_with($event->note, 'workspace.') ? __($event->note) : ($event->note === 'Заказ создан гостем через каталог' ? __('guest.created_via_catalog') : $event->note) }}</p>@endif</div></div>@endforeach</div></section></div>
<div class="guest-help-note"><i class="bi bi-telephone-x"></i><span><strong>{{ __('guest.calls_unavailable_title') }}</strong><small>{{ __('guest.calls_unavailable') }}</small></span></div>
@endsection
